"""
Django settings for online_coding_classroom project.

Generated by 'django-admin startproject' using Django 3.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os
import sys
# import mimetypes
# mimetypes.add_type("text/css", ".css", True)
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
#PROJECT_ROOT = os.path.abspath(os.path.dirname(__file__))
# TEMPLATE_DIRS = [os.path.join(os.path.dirname(__file__) ,'../templates').replace('\\','/')]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Variables below are stored in the Heroku app environment variables
SECRET_KEY = os.environ.get('SECRET_KEY')
DB_USER = os.environ.get('DB_USER')
DB_PASS = os.environ.get('DB_PASS')


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Only localhost for testing, and Heroku domains are allows to host this application
ALLOWED_HOSTS = ['online-coding-classroom.herokuapp.com',
                 'onlinecodingclassroomdev.herokuapp.com',
                 'localhost']

AUTH_USER_MODEL = "user.User"
AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.AllowAllUsersModelBackend',
    'user.backends.CaseInsensitiveModelBackend',
)


# Application definition
INSTALLED_APPS = [
    'user',
    'classroom_main',
    'lesson',
    'crispy_forms',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

# Added whitenoise for use of static files in Heroku
MIDDLEWARE = [
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'online_coding_classroom.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'classroom_main/templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'online_coding_classroom.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

### USE BELOW FOR CONNECTING TO A LOCALHOST DATABASE ###

# DATABASES = {
#     'default': {
#         'ENGINE': 'djongo',
#         'NAME': 'OnlineCodeClassroom',
#         'ENFORCE_SCHEMA': False,
#     }
# }

 ### USE BELOW CODE FOR CONNECTING TO A HOSTED DATABASE ###
# Database configurations for use of MongoDB through Djongo
if 'test' in sys.argv:
    DATABASES = {
        'default': {
            'ENGINE': 'djongo',
            'NAME': 'test_db'
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'djongo',
            'CLIENT': {
                'name': 'OnlineCodingClassroom',
                'host': f'mongodb+srv://{DB_USER}:{DB_PASS}@onlinecodingclassroom.sdmav.mongodb.net/OnlineCodingClassroom?retryWrites=true&w=majority',
                'username': DB_USER,
                'password': DB_PASS,
                'authMechanism': 'SCRAM-SHA-1'
                }
            }
        }


# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True



if 'test' in sys.argv:
    # Email settings for console backend email
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
else:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = 'smtp.gmail.com'
    EMAIL_PORT = 587
    EMAIL_USE_TLS = True
    EMAIL_HOST_USER = os.environ.get('EMAIL_USER')
    EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_PASS')



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

# Static files configurations
STATIC_ROOT = os.path.join(BASE_DIR,'staticfiles')
STATIC_URL = '/static/'

# Crispy configurations for use in template
CRISPY_TEMPLATE_PACK = 'bootstrap4'

# Login configurations
LOGIN_REDIRECT_URL = 'classroom-home'
LOGIN_URL = 'login'

