# Generated by Django 3.0.5 on 2020-11-16 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_name', models.CharField(max_length=15, unique=True)),
                ('description', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_title', models.CharField(max_length=20)),
                ('lesson_description', models.TextField(max_length=100)),
                ('lesson_code', models.TextField(max_length=300)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson.Language')),
            ],
        ),
        migrations.CreateModel(
            name='LessonHint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hint_title', models.CharField(max_length=15)),
                ('hint_description', models.TextField(max_length=40)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson.Lesson')),
            ],
        ),
    ]
