# Generated by Django 3.0.5 on 2020-11-09 16:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awardTitle', models.CharField(max_length=15)),
                ('description', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('languageName', models.CharField(max_length=15, unique=True)),
                ('description', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lessonTitle', models.CharField(max_length=20)),
                ('lessonDescription', models.TextField(max_length=100)),
                ('lessonCode', models.TextField(max_length=300)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom_main.Language')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schoolName', models.TextField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('grade', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='classroom_main.Lesson')),
            ],
        ),
        migrations.CreateModel(
            name='LessonHint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hintTitle', models.CharField(max_length=15)),
                ('hintDescription', models.TextField(max_length=40)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom_main.Lesson')),
            ],
        ),
        migrations.CreateModel(
            name='ComputingClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classNum', models.CharField(max_length=15)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom_main.School')),
            ],
        ),
    ]
